volumes:
  mysql_data:
  var_data:
  etc_data:

networks:
  defaultnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: freepbxint
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

secrets:
  mysql_root_password:
    file: mysql_root_password.txt
  freepbxuser_password:
    file: freepbxuser_password.txt
  postfix_sasl_passwd:
    file: sasl_passwd.txt

services:
  db:
    restart: always
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: freepbxuser
      MYSQL_PASSWORD_FILE: /run/secrets/freepbxuser_password
    secrets:
      - mysql_root_password
      - freepbxuser_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      defaultnet:
        ipv4_address: 172.20.0.10

  freepbx:
    restart: always
    image: escomputers/freepbx:17
    cap_add:
      - NET_ADMIN
    hostname: freepbx-docker.jsmwebrtc.my.id
    volumes:
      - var_data:/var
      - etc_data:/etc
      #- /opt/freepbx-data/recording:/var/spool/asterisk/monitor
      #- /opt/freepbx-data/conf:/etc/asterisk
      #- /opt/freepbx-data/log:/var/log/asterisk
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      defaultnet:
        ipv4_address: 172.20.0.20
    ports:
      - "80:80/tcp" # http
      - "443:443/tcp" # https
      - "8088:8088/tcp" # ws
      - "8089:8089/tcp" # wss
      - "5060:5060/tcp" # standard sip
      - "5060:5060/udp" # standard sip
      - "5061:5061/tcp" # standard sip-tls
      - "5061:5061/udp" # standard sip-tls
      - "50633:50633/tcp" # custom sip-tls
      - "50633:50633/udp" # custom sip-tls
    secrets:
      - postfix_sasl_passwd
    depends_on:
      - db
